// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWLj4ihMk44eobfW8KK1-iaRkpj5oXCf0',
    appId: '1:840689900833:web:b42bd9f45c234e625e3260',
    messagingSenderId: '840689900833',
    projectId: 'tontine-manager-sn-2026',
    authDomain: 'tontine-manager-sn-2026.firebaseapp.com',
    storageBucket: 'tontine-manager-sn-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnG16dV-lEGs890LPinStORCbvcv40iYA',
    appId: '1:840689900833:android:5166010a065f7d675e3260',
    messagingSenderId: '840689900833',
    projectId: 'tontine-manager-sn-2026',
    storageBucket: 'tontine-manager-sn-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcltnv0AABEJAHNTKGGGG1erHK_9PHwS0',
    appId: '1:840689900833:ios:7b26f85dec7fa4645e3260',
    messagingSenderId: '840689900833',
    projectId: 'tontine-manager-sn-2026',
    storageBucket: 'tontine-manager-sn-2026.firebasestorage.app',
    iosBundleId: 'com.tontinemanager.tontineManager',
  );
}
